### ISSUE TITLE
Subclass Constructor Signature Dependency

### ISSUE THREAD

**Issue by sgrtho** [poelstra/ts-promise#12]
I just came across this line of code during testing, which is from `Promise.ts`:

    var slave = new (Object.getPrototypeOf(this).constructor)(internalResolver);

I find this a very strange design choice. This particular line of code implies that any subclass has a compatible constructor signature (taking a resolver as an argument).

Subclassing `Promise` with a non-compatible constructor signature may look unintuitive or misleading, I admit. But let's put that aside for a moment. Having an implicit subclass constructor signature (without type safety) seems really weird to me.  E.g.: the following example will behave erroneous, setting up two timeouts, leading to an assertion, eventually:

    import Promise from "ts-promise";
    
    class ResolveInOneSecPromiseImp extends Promise<null> {
      constructor() {
        super((resolve, reject) => {
          setTimeout(() => {
            resolve(null);
          }, 1000);
        })
      }
    }

Am I missing something here? Is it a good idea to request that much knowledge about your implementation from a subclassing monkey like me? :-)

**Comment by poelstra** [comment]
@sgrtho I fully agree it's a bit tricky, especially - as you noted - it won't be enforced by the compiler.

The reason for doing this is because it's 'prescribed' by the spec. Please also see #11, which is basically about the same. I've added some more background in that issue.

Given that this is the second time this has come up, and I've run into it myself too before (although I learned to use a different 'pattern' then), I'm wondering if I can either warn for this behaviour, and/or provide a workaround. I've seen things about `@@species`, might have to dig into this further.

I'll leave this issue open for now, to try to think of a way to prevent accidental errors like you mentioned.

**Comment by sgrtho** [comment]
Thanks for your response. Sorry, not sure why I missed the other issue. So, if one would like to extend a Promise for the purpose of wrapping `setTimeout`, including an `abort` method, how would that be done cleanly? Like that? Looks awful!

    import Promise, { Thenable } from "ts-promise";

    interface DelayPromise extends Promise<null> {
      abort() : DelayPromise;
    }

    class TimerBufferingPromiseImp extends Promise<null> {
      private _internalTimer: any = null;

      constructor(resolver: (resolve: (value: Thenable<null> | null) => void, reject: (reson: Error) => void) => void) {
        super((resolve, reject) => {
          return resolver(resolve, reject);
        });
      }

      public abort() {
        if(this._internalTimer !== null) {
          clearTimeout(this._internalTimer);
          this._internalTimer = null;
        }

        return this;
      }

      public __setTimer(timer: number) {
        this._internalTimer = timer;
        return this;
      }
    }

    function wait(duration: number) : DelayPromise {
      let
        timer        : number                   = 0,
        delayPromise : TimerBufferingPromiseImp = new TimerBufferingPromiseImp((resolve, reject) => {
          timer = setTimeout(() => {
            resolve(null);
          }, duration);
        })
        ;

      return delayPromise.__setTimer(timer);
    }

    export default wait;

    export {
      DelayPromise as Promise,
      TimerBufferingPromiseImp as mainImplementation,
      wait
    }
 
Awful! Cannot pass parameters into the constructor, cannot resolve from the outside. I couldn't dig up something nice (having a subclass with abort capabilities and type safety). Any suggestions?

**Comment by poelstra** [comment]
Although I agree this (having an abort() on the promise itself) seems like a good idea, I wonder whether using a sub-class for this is really the 'right thing to do'; your request looks a lot like Cancellable Promises, and although there's been a lot of discussion on them, I don't think consensus has been reached yet.

For example, in your case, note that the `abort()` method doesn't get transferred to derived Promises (e.g. on `.then()`). And doing so is far from trivial (consider promises being combined with `.all()`, or multiple calls to `.then()` on the same promise, and then one of them calling `abort()`).

So, when you chain a `.then()` call, you'd either want to:
- return a 'plain' Promise (without `.abort()`), or
- return a new DelayPromise, in which case you'd somehow need to pass the `abort()` 'up the chain'.

(Note that although ts-promise does create a new instance of the 'sub-promise' when you call `.then()`, the typings cannot currently correctly reflect that, because returning a polymorphic `this` with a different type parameter isn't possible with TS yet).)

Having said all that, here's what I think is a somewhat cleaner way of achieving your goal:
```ts
import Promise from "ts-promise";

export class DelayPromise extends Promise<void> {
	private _timer: any;

	public abort(): void {
		if (this._timer) {
			clearTimeout(this._timer);
			this._timer = undefined;
		}
	}

	public static wait(timeout: number): DelayPromise {
		let resolver: (v?: void) => void;
		const p = new DelayPromise((r) => { resolver = r; });
		p._timer = setTimeout(() => {
			resolver();
			p._timer = undefined;
		}, timeout);
		return p;
	}
}

export default DelayPromise;
```

Usage:
```ts
const promise = DelayPromise.wait(1000);
promise.then(...);
promise.abort();
```

Again, to be honest, I suppose your best bet is actually indeed using some kind of free function (like your `wait()`), and making the abort method an explicit and independent 'thing'.
For example, here's two subtly different ways of doing this.

First, here's something similar to a `Deferred`:
```ts
interface AbortableWait {
	promise: Promise<void>;
	abort: () => void;
}

function wait(timeout: number): AbortableWait {
	let timer: any;
	function abort(): void {
		if (timer) {
			clearTimeout(timer);
			timer = undefined;
		}
	};
	return {
		promise: new Promise<void>((resolve) => {
			timer = setTimeout(
				() => {
					resolve(undefined);
					timer = undefined;
				},
				timeout
			);
		}),
		abort: abort
	};
}
```

The following version uses the revealing constructor pattern:
```ts
function wait(timeout: number, aborter: (abort: () => void) => void): Promise<void> {
	let timer: any;
	function abort(): void {
		if (timer) {
			clearTimeout(timer);
			timer = undefined;
		}
	};
	return new Promise<void>((resolve) => {
		aborter(abort);
		timer = setTimeout(
			() => {
				resolve(undefined);
				timer = undefined;
			},
			timeout
		);
	});
}
```

Usage examples (which directly call abort, but you catch the drift):
```ts
// AbortableWait version
const aw = wait(1000);
aw.promise.then(...);
aw.abort();

// Revealing Constructor version
const promise = wait(1000, (abort) => {
	abort();
});
promise.then(...);
```

The advantage of these versions is that there's no confusion at all about what happens to the abort method on chained promises etc, the abort function can be passed independently from the promise.

What do you think?

**Comment by sgrtho** [comment]
First of all, I want to thank you: for your project in general and for your comments in this thread. This really helped me lot - being quite new to this promise thing. As to your code samples:

I haven't at all thought about a static method, which makes injecting the timer reference way cleaner - good thinking!

I now fully understand that deriving from Promise probably isn't the right mean to wrap this up. I guess it never was a good choice to think of it as an *is-a* relationship. It just seemed so tempting to have the *then* syntax, with all the rest of the methods, directly acessible as a result of the free wait function. Didn't think that much about chaining.

Still, if you can think of anything to prevent or warn about these kind of situations, where a derivated constructor fails or may fail to comply, it may help some people. I myself lost quite a lot of time digging this up from somewhere deep inside a failing, seemingly unrelated unit test. Much appreciated.

**Comment by poelstra** [comment]
Thanks for the kind words!

I'll give the warning/prevention some more thought...
