### ISSUE TITLE
Broken build on 0.3.2

### ISSUE THREAD

**Issue by OliverUv** [poelstra/ts-promise#13]
Hello ~

Just wanted to note that our builds broke on between 0.3.1 and 0.3.2.

When you change functionality that affects the build system in such a major way as to force people to upgrade to TS 2.0, please do increase the minor or major digit in semver, not just the patch level digit.

(Also, thanks for a very nice library. :) )

**Comment by poelstra** [comment]
Thanks for the report! I'm very sorry to have broken your builds, I tend to carefully stick to semver, and didn't expect these changes to actually break older builds...

Can you please let me know how your build was broken exactly? Maybe I can publish a new version that remains compatible...

**Comment by OliverUv** [comment]
Oh hi, sorry I didn't get back to you earlier. Discovery of .d.ts files for declarations seem to be what broke it. I assume it had something to do with your updating the definitions to work with TS2.0 that broke it for TS1.8.

**Comment by poelstra** [comment]
Ran into it on another project, too. Problem was that TS generated a strange (and unnecessary) dependency on the node typings in some of the generated .d.ts files. Apparently because of using the Error type.

Anyway, it's fixed in 0.3.3 (which should be backwards compatible to both 0.3.1 and 0.3.2).
