### ISSUE TITLE
Catch Reason Typing

### ISSUE THREAD

**Issue by sgrtho** [poelstra/ts-promise#15]
Hi!

After years of using `ts-promise` we still stick to it. It's solid. Thanks for that.

Have you ever thought of changing the catch typing? Currently you type the `reason` as `Error`, but as the following real real world use case demonstrates, it's not always true:

    (new Promise(resolve => {
      throw null;
    }))
    .catch(reason => {
      console.log(reason.stack);
    })
    .catch(reason => {
      console.log(reason.stack);
    });

The TypeScript typing for `catch(reason)` is `any`, which I'd prefer in `ts-promise` as well. It won't give any additional type safety, but I tend to think of it as *more correct*.

**Comment by poelstra** [comment]
Thanks for the kind words, glad you like it :)

You're absolutely right. Although it's 'not nice' to throw something that's not an Error, it is indeed possible.
I did it because of convenience, although I've also always wondered whether it was the smart thing to do...

I'll change it.

**Comment by poelstra** [comment]
While changing it, I wondered what would be best: also change things like `Promise.reject()` to accept non-`Error`, or leave these 'strong'. I suppose most people (especially TS people?) won't be injecting non-Errors into these anyway, and one could always cast via `any` if needed (the lib supports it fine, of course).

Wondering if you have a good argument for either case?

**Comment by sgrtho** [comment]
I do *throw* or *reject* using `null` in one or two peaces of software. The code base in which I spend most of my time uses an `... extends Error` type to achieve comparable behavior. The conclusion I got:

- First of all subclassing 'Error' isn't hassle-free, as you know. In addition 90% of the errors thrown are `MissingPriviledgesError` or `UserInteractionCancelledError` and stuff like that, which are *expected errors* mostly. In order to auto-handle *catches* I needed a central dependency which defines those errors.
- Using `null` on the other hand avoids all this overhead. But the moment one of those components is part of an external Promise flow, it has the potential to create a mess, giving me an unsafe gut feeling about how I need to handle it every single time. The only true benefit I see here, is the fact that it's hard to miss when you're trying to access a property on 'null' while testing.

I encourage the `any` on *catch* but I wouldn't promote it for *reject*. As you said, cast it. That way it has the level of attention it should have.

**Comment by sgrtho** [comment]
But there's one more thing, while we're at it: can you think of a way to refine the typing for the *revealing constructor resolver*, and probably the `deferred resolver` to work without an argument if it's a void type?

We use `null` promises throughout. But the only true reason behind this, is the fact that we promote 'null' over 'undefined' or 'void 0' for resolving.

I'm not sure if the latest type system even supports it, because making the argument optional in general truly isn't an option.

**Comment by poelstra** [comment]
Ok, I'll leave `reject()` etc as-is (with 'strong' Error argument), but will make `catch()` (without an Error predicate) pass `any` to its callback. Thanks for the feedback!

I agree that using derived classes of Error is problematic. due the inheritance issues, and due to multiple versions of the same 'sort' of class being present in large apps. It seems this is one of the reasons why  Node is switching to string-based error codes.

---

About the other issue: resolving with `null`, that's a good one. Actually, I almost completely stopped using `null`, and instead use `undefined`. Because the TS code-base does the same, and it makes sense because uninitialized values (and e.g. default function args) are also `undefined`, not `null`.
The only places where I still use `null` is `Object.create(null)` and if I need to serialize an otherwise empty value in JSON.

I do have some constructs to automatically get a `Promise<void>` work the easy way in certain cases (e.g. if you do `Promise.resolve()`, or `somePromise.return()`), but as far as I know the construct you're suggesting is indeed not possible yet in TS.

Also note that there is a special type `VoidDeferred`, which allows calling its `resolve()` without an argument.

There have been several proposals to enable this in general in TS, such as making `someFunc<T>(f: T)` behave like `someFunc<T>(f?: T)` in case T happens to be `void`.

To work around this, the Promise typing in TS itself always makes the resolve argument optional, which is a very bad thing to do, in my opinion. So I opt for explicitly calling `resolve(undefined)` in the few cases where that's really necessary...

(Note: if you like to discuss this second part further, please open a new issue for it.)

**Comment by poelstra** [comment]
Fixed in v1.0.0, thanks!
