### ISSUE TITLE
variable setImmediate should not be a global variable

### ISSUE THREAD

**Issue by Acefox17** [poelstra/ts-promise#8]
If you imported setImmediate from node timers instead of using a global variable, problems when using ts-promise with browserify would go way.
![screen shot 2016-01-28 at 6 42 45 pm](https://cloud.githubusercontent.com/assets/3476639/12665799/430c204e-c5ef-11e5-93b6-274d6c9961e0.png)

**Comment by poelstra** [comment]
Hmm, interesting...
It seems a bit strange that `setTimeout()` is available in browserify, but `setImmediate()` isn't.

Anyway, I considered switching back to `process.nextTick()` (now that it no longer has 'special' behaviour for long chains of calls), so that should also solve your issue.

I'll look at it this weekend.

**Comment by poelstra** [comment]
Changing to `process.nextTick()` could change behaviour for some programs, so decided to defer that to a later (major) version.

It does work with browserify now (by using `setTimeout` instead of `setImmediate`, if it's not available).

Released in v0.2.4.

Thanks for reporting!
